import logging

logger = logging.getLogger(__name__)

DISCLAIMER_TEXT = (
    "DISCLAIMER: This report was generated by an Artificial Intelligence system. "
    "It is NOT a medical diagnosis and should not be used as a substitute for "
    "professional medical advice, diagnosis, or treatment. Always seek the advice "
    "of your physician or other qualified health provider."
)

def verify_report_safety(final_report: dict) -> dict:
    """
    Acts as the Safety & Compliance Layer (Layer 9).
    Ensures that the final report contains necessary disclaimers and checks for 
    high-confidence diagnoses of life-threatening conditions to append warnings.
    """
    logger.info("Running safety verification on final report...")
    
    # 1. Always append the medical disclaimer
    final_report["safety_disclaimer"] = DISCLAIMER_TEXT
    
    # 2. Flag high-urgency items
    critical_alerts = []
    
    # Check recommended steps for 'Emergent'
    if "recommended_steps" in final_report:
        for step in final_report["recommended_steps"]:
            urgency = step.get("urgency", "").lower()
            if urgency in ["emergent", "urgent"]:
                critical_alerts.append(f"CRITICAL ACTION RECOMMENDED: {step.get('action')}")
                
    # 3. If confidence is extremely high on a severe diagnosis, 
    # we still force the disclaimer to the top of the UI
    if final_report.get("confidence_score", 0.0) >= 0.90:
        critical_alerts.append("High-confidence finding detected. Human clinical correlation is mandatory.")

    final_report["critical_alerts"] = critical_alerts
    final_report["safety_verified"] = True
    
    return final_report
